### PR TITLE
Fix spelling in introduction chapter

### PR DESCRIPTION
**Pull request by Sam-Kruglov**
This is to clarify https://github.com/AxonIQ/reference-guide/issues/79 
By this, I want to emphasize the need for some sort of spell checker in the CI of this project.
I used [Grammarly](https://www.grammarly.com) to manually check the spelling, but I believe they don't have any API or CLI.
Screen Shot 2019-05-21 at 11 23 03

### CODE REVIEW

**Comment by Sam-Kruglov** [comment]
Also, some URLs are broken (e.g. in here https://docs.axoniq.io/reference-guide/implementing-domain-logic/command-handling). Maybe add a job that seeks all links and pings them for 200 OK

**Comment by Sam-Kruglov** [comment]
Also, I see that you write the code examples right in the docs. I don't know if GitBook allows that, but Hibernate use actual references to GitHub repo in their docs https://github.com/hibernate/hibernate-orm/tree/master/documentation

**Comment by Sam-Kruglov** [comment]
changed email in commit

**Comment by smcvb** [comment]
Thanks for your interest in improving the Reference Guide, @Sam-Kruglov. 

Some spell checker being part of the pull request process would be beneficial, indeed. I however believe we have had future experience using Grammarly for verification, but not always with desired results. From the shared PR in here, I already spot a couple of 'resolution' from the spell checker which are style driven decisions we intentionally have put in the reference guide. I'd thus like to state that a spell checker should not be the golden bullet, but more so provided suggestions.

Secondly, I'd like to point out that you're utilizing a 'spelling' pull request to suggest different additions next to spelling. All of these justify a discussion, but I don't feel _this_ issue is the right place to add all your suggestions to. If you feel strongly about them, I'd like to request that you add new issues for every separate improvement you have.

Thanks again for your interest, @Sam-Kruglov, we'll take your idea into account!

**Comment by Sam-Kruglov** [comment]
Thanks for your reply, @smcvb!

I understand that some suggestions from Grammarly may not be correct, but you definitely can't argue with a missing article of a wrong verb form.

This PR only intends to fix some spelling in the introduction chapter, nothing more. It also cross-references issue 79 which says "Use a spell checker" which is just a suggestion, since it is not a PR. 
I see the PR and the issue very clear, could you elaborate what more separation do you need?

**Comment by smcvb** [comment]
Great, thanks for adding those issues @Sam-Kruglov!

> I understand that some suggestions from Grammarly may not be correct, but you definitely can't argue with a missing article or a wrong verb form.

Just to make things clear, I definitely do not intend to argue with a spell checker! 
I am not a native English speaker to begin with, so guidance along these lines is still valuable.

**Comment by smcvb** [comment]
We have taken the stance to introduce some of the suggestions shared in the PR if they are correct/applicable. These separate changes have been included in commit 9623bbb. As such I regard this PR as resolved and thus I will close it.
Thanks for the effort Sam!

**Pull request closed without merging**
